% by Christian Delacroix (2014)

function str = meepMakeBlock(dn,dC,ds,de1,de2,de3)

str = ['(make block ' ...
    '(material (make dielectric (index ' num2str(dn) ')))' ...
    '(center ' num2str(dC(1)) ' ' num2str(dC(2)) ' ' num2str(dC(3)) ')' ...
    '(size ' num2str(ds(1)) ' ' num2str(ds(2)) ' ' num2str(ds(3)) ')' ...
    '(e1 ' num2str(de1(1)) ' ' num2str(de1(2)) ' ' num2str(de1(3)) ')' ...
    '(e2 ' num2str(de2(1)) ' ' num2str(de2(2)) ' ' num2str(de2(3)) ')' ...
    '(e3 ' num2str(de3(1)) ' ' num2str(de3(2)) ' ' num2str(de3(3)) '))\n'];